### ISSUE TITLE
Folder completion not work

### ISSUE THREAD

**Issue by Nattle** [toumorokoshi/tome#28]
Using zsh on OSX

I have a folder in the root level of my structure. Running my script with that folder name correctly says that it's a folder. When I try and tab complete it only prints out the root level commands instead of the item in that folder. 

OIddly, this doesn't work for one of my commands but does work for another. Both are declared in my startup scripts the same way. 

Working command `to`
![working](https://user-images.githubusercontent.com/2287972/159287836-e615c3a8-8908-4260-9734-14ce858dad96.png)

Broken command `app`
<img width="1292" alt="broken" src="https://user-images.githubusercontent.com/2287972/159287837-f56f6014-d626-4e1d-8042-5b50a7f83d93.png">

**Comment by toumorokoshi** [comment]
thanks for the bug report! 

would you mind trying this the [0.8.0b0 version I just released](https://github.com/toumorokoshi/tome/releases/tag/v0.8.0b0) and see if you run into the same issue? I can't confirm it, but I think some of the inconsistent behavior around directories was caused by the hand-written handling of commands. Now that it's based on clap-rs I think it helps resolve some of the weirdness.

If that doesn't fix it, would you mind sending back the output of:

    tome-osx command-complete $TO_DIR -- connector
    tome-osx command-complete $APP_DIR -- what 

This should at least help figure out if there's something special about those directories, or it's an issue in the completion handling side.

**Comment by Nattle** [comment]
<img width="1250" alt="Screen Shot 2022-03-24 at 10 28 26 AM" src="https://user-images.githubusercontent.com/2287972/159938655-0f2973ae-339b-4f0d-85ef-a0ff9ef40446.png">
[app.zip](https://github.com/toumorokoshi/tome/files/8342317/app.zip)

Still not working with that new binary.  I attached a zip of the folder in case that helps. Permissions seem ok as well, both are 755 and owned by my user and staff. 

Here's the command I use to setup app, I also tried in bash and get the same thing.
export APP_DIR=~/repos/scripts/app
if [ -d "$APP_DIR" ]; then
	eval "`~/bin/tome-osx init app $APP_DIR zsh`"
fi

**Comment by toumorokoshi** [comment]
Okay, tracked it down to a bad completion shell function. Please give 0.8.1 a try and let me now if that doesn't fix it.

**Comment by Nattle** [comment]
Yup, that fixed it. :)

Thanks for the great tool.
